# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zK8XLsCD-rrMT2DGUIsqYPgRQgOxzz5
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
data = pd.read_csv('data.csv')
X = data[['Hours']]
y = data['Score']
model = LinearRegression()
model.fit(X, y)
predicted = model.predict(X)
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, predicted, color='red', label='Regression Line')
plt.xlabel("Hours Studied")
plt.ylabel("Score")
plt.title("Linear Regression from CSV")
plt.legend()
plt.grid(True)
plt.show()
hours = [[12]]
predicted_score = model.predict(hours)
print(f"Predicted Score for 12 hours: {predicted_score[0]:.2f}")